version: "3.8"  # https://matsuand.github.io/docs.docker.jp.onthefly/compose/compose-file/compose-versioning/
services:
  app:
    build: ./infra/php
    volumes:
      - ./web:/work
  web:
    image: nginx:1.19.5-alpine  # https://hub.docker.com/_/nginx?tab=tags&page=1&ordering=last_updated
    ports:
      - 10080:80
    volumes:
      - ./web:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: